name: Create and attach artifact to release

on:
  push:
    tags:
      - 'v*'

jobs:
  attach_artifact:
    name: Attach artifact to release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "docker-compose.yml"
          token: ${{ github.token }}
    